import Icon from "../icon/Icon";
import React from "react";
import "./equipmentSlot.scss";

export const Ammo = () => <span className="equipmentSlot ammo"><Icon type="ammo"/>Ammo</span>;
export const Back = () => <span className="equipmentSlot back"><Icon type="back"/>Back</span>;
export const Bag = () => <span className="equipmentSlot bag"><Icon type="bag"/>Bag</span>;
export const Chest = () => <span className="equipmentSlot chest"><Icon type="chest"/>Chest</span>;
export const Feet = () => <span className="equipmentSlot feet"><Icon type="feet"/>Feet</span>;
export const Finger = () => <span className="equipmentSlot finger"><Icon type="finger"/>Finger</span>;
export const Hands = () => <span className="equipmentSlot hands"><Icon type="hands"/>Hands</span>;
export const Head = () => <span className="equipmentSlot head"><Icon type="head"/>Head</span>;
export const Legs = () => <span className="equipmentSlot legs"><Icon type="legs"/>Legs</span>;
export const Mainhand = () => <span className="equipmentSlot mainhand"><Icon type="mainhand"/>Main hand</span>;
export const Neck = () => <span className="equipmentSlot neck"><Icon type="neck"/>Neck</span>;
export const Ranged = () => <span className="equipmentSlot ranged"><Icon type="ranged"/>Ranged</span>;
export const Relic = () => <span className="equipmentSlot relic"><Icon type="relic"/>Relic</span>;
export const Secondaryhand = () => <span className="equipmentSlot secondaryhand"><Icon type="secondaryhand"/>Secondary hand</span>;
export const Shirt = () => <span className="equipmentSlot shirt"><Icon type="shirt"/>Shirt</span>;
export const Shoulder = () => <span className="equipmentSlot shoulder"><Icon type="shoulder"/>Shoulder</span>;
export const Tabard = () => <span className="equipmentSlot tabard"><Icon type="tabard"/>Tabard</span>;
export const Trinket = () => <span className="equipmentSlot trinket"><Icon type="trinket"/>Trinket</span>;
export const Waist = () => <span className="equipmentSlot waist"><Icon type="waist"/>Waist</span>;
export const Wrists = () => <span className="equipmentSlot wrists"><Icon type="wrists"/>Wrists</span>;
